name: noise_meter_flutter
description: Sound meter

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.0
  noise_meter: ^2.0.0
  syncfusion_flutter_charts: ^18.3.50
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
